### ISSUE TITLE
support tf1.* ?

### ISSUE THREAD

**Issue by RanFeng** [VoVAllen/tf-dlpack#10]
it's a wonderful work! i want to know will it support tensorflow 1.*.* ? thanks for your reply!

**Comment by VoVAllen** [comment]
Hi,

It's hard to implement this for tf 1.0 since it's based on symbolic execution, which prevents sending PyCapsule between symbols. One possible alternative you can refer to is tobe's implementation with [tftvm](https://github.com/tobegit3hub/tftvm), which packs the external computation into a custom op.

**Comment by VoVAllen** [comment]
Although I can see some work around to solve this, but the code would be ugly. Also since tf 1.0 will be gradually deprecated. I'm not considering to implement it on tf1.0.
